# Generated by Django 6.0.3 on 2026-03-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='supply_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseslip',
            name='memo',
        ),
    ]
