# Generated by Django 6.0.3 on 2026-03-11 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('core', '0001_initial'),
        ('purchase', '0002_remove_purchaseitem_supply_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='supply_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseslip',
            name='memo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='core.company'),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_slips', to='core.company'),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_slips', to='companies.customer'),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='supply_amount',
            field=models.IntegerField(default=0, verbose_name='공급가액'),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='합계'),
        ),
        migrations.AlterField(
            model_name='purchaseslip',
            name='vat_amount',
            field=models.IntegerField(default=0, verbose_name='부가세'),
        ),
    ]
