# Generated by Django 6.0.3 on 2026-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseitem_supply_amount_purchaseitem_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseslip',
            name='slip_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
