# Generated by Django 6.0.3 on 2026-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('business_number', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('credit_limit', models.IntegerField(default=0, verbose_name='여신한도')),
                ('current_balance', models.IntegerField(default=0, verbose_name='현재잔액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
