# Generated by Django 6.0.3 on 2026-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesslip',
            name='slip_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
