# Generated by Django 6.0.3 on 2026-03-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='품목코드')),
                ('name', models.CharField(max_length=255, verbose_name='품목명')),
                ('maker', models.CharField(blank=True, max_length=100, verbose_name='메이커')),
                ('category_l', models.CharField(blank=True, max_length=100, verbose_name='대분류')),
                ('category_m', models.CharField(blank=True, max_length=100, verbose_name='중분류')),
                ('category_s', models.CharField(blank=True, max_length=100, verbose_name='소분류')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='바코드')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('cost_price', models.IntegerField(default=0, verbose_name='매입단가')),
                ('sale_price', models.IntegerField(default=0, verbose_name='판매단가')),
                ('vat_type', models.CharField(choices=[('TAX', '과세'), ('ZERO', '영세'), ('EXEMPT', '면세')], default='TAX', max_length=10, verbose_name='부가세구분')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'name'], name='products_pr_company_28b2e6_idx'), models.Index(fields=['company', 'barcode'], name='products_pr_company_e22fd0_idx')],
                'unique_together': {('company', 'sku')},
            },
        ),
    ]
