# Generated by Django 6.0.3 on 2026-03-05 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='품목코드')),
                ('name', models.CharField(max_length=255, verbose_name='품명')),
                ('spec', models.CharField(blank=True, max_length=255, verbose_name='규격')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='단위')),
                ('maker', models.CharField(blank=True, max_length=100, verbose_name='메이커명')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='바코드')),
                ('cost_price', models.IntegerField(default=0, verbose_name='매입단가')),
                ('sale_price', models.IntegerField(default=0, verbose_name='판매단가')),
                ('vat_type', models.CharField(choices=[('TAX', '과세'), ('ZERO', '영세'), ('EXEMPT', '면세')], default='TAX', max_length=10, verbose_name='부가세구분')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('SALE_ITEM', '매출전표 품목'), ('PURCHASE_ITEM', '매입전표 품목'), ('ADJUST', '재고조정')], max_length=30)),
                ('source_id', models.IntegerField()),
                ('qty_change', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_txs', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_txs', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='현재고')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'sku'], name='products_pr_company_e57b48_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'name'], name='products_pr_company_28b2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'barcode'], name='products_pr_company_e22fd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku')},
        ),
        migrations.AddIndex(
            model_name='inventorytx',
            index=models.Index(fields=['company', 'product'], name='products_in_company_799f40_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytx',
            index=models.Index(fields=['tx_type', 'source_id'], name='products_in_tx_type_9ce634_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytx',
            constraint=models.UniqueConstraint(fields=('tx_type', 'source_id'), name='uniq_tx_type_source'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('company', 'product'), name='uniq_inventory_company_product'),
        ),
    ]
